### ISSUE TITLE
Resampled image support

### ISSUE THREAD

**Issue by LetrixZ** [LetrixZ/faccina#1]
- ~~Allow user to select in the reader if they want resampled or not.~~
- Add resampled download option ~~and allow to set default for the user.~~

**Comment by nayumiDEV** [comment]
We can use https://wsrv.nl/ for this, that will reduce server load.

**Comment by LetrixZ** [comment]
I prefer to not rely on any 3rd party services.

The structure for resampled images already exists, I just need to add the support to show them on the reader.

**Comment by nayumiDEV** [comment]
> I prefer to not rely on any 3rd party services.
> 
> The structure for resampled images already exists, I just need to add the support to show them on the reader.

I just want to make sure this won't cause the server to store duplicate image files of different sizes?

**Comment by UBTL** [comment]
Gretings, I would like to ask if there is a way to rather than read a zip file, read the decompressed folder/images directly from the content folder or some other folder similar to the the thumbnails, ideally for loadbalancing/CDN reasons

**Comment by LetrixZ** [comment]
> Gretings, I would like to ask if there is a way to rather than read a zip file, read the decompressed folder/images directly from the content folder or some other folder similar to the the thumbnails, ideally for loadbalancing/CDN reasons

That could be possible, although I would put it behind an indexing option like `--unpack`.
ZIPs would still be needed as a base as they server as an anchor to the galeries.

**Comment by UBTL** [comment]
Im fine with keeping the zip backend stuff and but have an option to rather have the site directly use unpacked images/galleries instead rather than use the zip files

**Comment by UBTL** [comment]
Suddenly I noticed the project getting screamingly slow at times (I only have like 48 or so galleries loaded up for testing atm, I have done the generate-images stuff and Im running on the "cluster" mode and such) and went to look up some of the logs on the terminal and it said this  

[2024-12-01T04:58:38.849Z] resampledImage [ID 39] Page number 1 - Failed to encode image
 397 |                 if (entry.method === consts.STORED) {
398 |                     // nothing to do
399 |                 } else if (entry.method === consts.DEFLATED) {
400 |                     entryStream = entryStream.pipe(zlib.createInflateRaw());
401 |                 } else {
402 |                     return callback(new Error('Unknown compression method: ' + entry.method));
                                          ^
error: Unknown compression method: 14
      at /root/Desktop/faccina-main/node_modules/node-stream-zip/node_stream_zip.js:402:37
      at /root/Desktop/faccina-main/node_modules/node-stream-zip/node_stream_zip.js:480:13
      at node:fs:182:13

Thus why Im saying I would rather prefer have the decompressed galleries if I could since I dont have a way to check up 2TB+ worth of "content" to see if the zip files are "fine" or not

**Comment by LetrixZ** [comment]
I'll be adding support for unpacking images and using them instead of unzipping the file.

> error: Unknown compression method: 14

As for this error, it occurs because the file has been compressed with LZMA and the libraries that I currently use don't support this. They only DEFLATE and GZ.
I see if I can find a way to integrate 7zip to handle these archives.

**Comment by UBTL** [comment]
Alright then thank you, also I see on the terminal logs this error popping up at times, nothing is crashing though or similar so Im kind of ignoring it for now I guess

32 |    * @param {number} status
33 |    * @param {string} text
34 |    * @param {string} message
35 |    */
36 |   constructor(status, text2, message) {
37 |     super(message);
____^
error: Not found: /image/8363fca4a7a95fe4/03.png
      at new SvelteKitError (/root/Desktop/FReader/build/server/chunks/index.js:37:5)
      at /root/Desktop/FReader/build/server/index.js:2751:18
      at resolve2 (/root/Desktop/FReader/build/server/index.js:2647:27)
      at resolve (/root/Desktop/FReader/build/server/index.js:2584:34)
      at handle (/root/Desktop/FReader/build/server/chunks/hooks.server.js:6:16)
      at /root/Desktop/FReader/build/server/index.js:2582:43

Just reporting about it
