### ISSUE TITLE
Impossible to launch any bun command in this project

### ISSUE THREAD

**Issue by HeartBtz** [LetrixZ/faccina#25]
Hello, i systematicly have the same error even reinstalling completely from scratch, any ideas? knowing that I git pull each time, to be up to date :) 

```bash
root@CT110-Faccina /opt/faccina # bun start
$ bun ./serve.ts
530 |         result = new this._Promise((resolve, reject) => {
531 |           query.callback = (err, res) => (err ? reject(err) : resolve(res))
532 |         }).catch((err) => {
533 |           // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
534 |           // application that created the query
535 |           Error.captureStackTrace(err)
                      ^
error: permission denied for schema public
 code: "42501"

      at /opt/faccina/node_modules/pg/lib/client.js:535:17
      at processTicksAndRejections (native:7:39)
      at /opt/faccina/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:104:21
      at processTicksAndRejections (native:7:39)
```

Thanks

**Comment by HeartBtz** [comment]
of course I tested the database connection

**Comment by LetrixZ** [comment]
I haven't used the Postgres connection in a while. I'll check

**Comment by LetrixZ** [comment]
Ok. So I fixed a lot of Postgres related stuff that I found when trying it.

Although the error that you see is because the user that you try to use lacks permissions to edit the public schema.

EDIT: Let me know if it isn't a user permissions problem.
